---
csharp:
    displayName: C#
    steps:
        - file: "csharp/AgentState/Program.cs"
          highlight: "0-150"
        - file: "csharp/AgentState/Program.cs"
          highlight: "17-25"
        - file: "csharp/AgentState/Program.cs"
          highlight: "27-29"
        - file: "csharp/AgentState/Program.cs"
          highlight: "142-148"
        - file: "csharp/AgentState/Program.cs"
          highlight: "31-38"
        - file: "csharp/AgentState/Program.cs"
          highlight: "117-134"
        - file: "csharp/AgentState/Program.cs"
          highlight: "94-109"
        - file: "csharp/AgentState/Program.cs"
          highlight: "40-41"
        - file: "csharp/AgentState/Program.cs"
          highlight: "43-44"
        - file: "csharp/AgentState/Program.cs"
          highlight: "60-86"
        - file: "csharp/AgentState/Program.cs"
          highlight: "46-47"
java:
    displayName: Java
    steps:
        - file: "java/src/main/java/Main.java"
          highlight: "0-208"
        - file: "java/src/main/java/Main.java"
          highlight: "23-31"
        - file: "java/src/main/java/Main.java"
          highlight: "33-38"
        - file: "java/src/main/java/Main.java"
          highlight: "125-160"
        - file: "java/src/main/java/Main.java"
          highlight: "40-47"
        - file: "java/src/main/java/Main.java"
          highlight: "104-117"
        - file: "java/src/main/java/Main.java"
          highlight: "82-96"
        - file: "java/src/main/java/Main.java"
          highlight: "49-52"
        - file: "java/src/main/java/Main.java"
          highlight: "54-55"
        - file: "java/src/main/java/Main.java"
          highlight: "66-74"
        - file: "java/src/main/java/Main.java"
          highlight: "57-58"
